### ISSUE TITLE
Unable to download kenlm-20200308_.tar.gz when install from source

### ISSUE THREAD

**Issue by alex1iam** [synesthesiam/voice2json#15]
Hello 
When running make, i see the following error: curl -sSfL -o "/root/voice2json/download/kenlm-20200308_armv7.tar.gz" "https://github.com/synesthesiam/prebult-apps/releases/download/v1.0/kenlm-20200308_.tar.gz"
curl: (22) The requested URL returned error: 404 Not Found
 where i can get package?
thanks!

**Comment by synesthesiam** [comment]
Should be fixed now in `master`
