### ISSUE TITLE
Unable to download phonetisaurus-2019.tar.gz when install from source

### ISSUE THREAD

**Issue by ppvastar** [synesthesiam/voice2json#2]
Thanks for this great project!

When running install.sh, the following error arise:

Downloading phonetisaurus (https://github.com/synesthesiam/phonetisaurus-2019/releases/download/v1.0/phonetisaurus-2019.tar.gz)
curl: (22) The requested URL returned error: 404 Not Found

Seems that the file is missing. Could you please check? 

Thanks!

**Comment by koenvervloesem** [comment]
See https://github.com/synesthesiam/rhasspy/issues/134
