### ISSUE TITLE
Un-able to complete make when compiling from source

### ISSUE THREAD

**Issue by infinitymakerspace** [synesthesiam/voice2json#20]
I am receiving the following error that stops from make completing

pi@raspberrypi:~/voice2json $ make
/bin/mkdir -p "/home/pi/voice2json/download"
/bin/mkdir -p "/home/pi/voice2json/build"
curl -sSfL -o "/home/pi/voice2json/download/kenlm-20200308_armv7.tar.gz" "https://github.com/synesthesiam/prebult-apps/releases/download/v1.0/kenlm-20200308_armv7.tar.gz"
curl: (22) The requested URL returned error: 404 Not Found
make: *** [Makefile:342: /home/pi/voice2json/download/kenlm-20200308_armv7.tar.gz] Error 22

**Comment by synesthesiam** [comment]
Thanks for catching this, I misspelled "prebuilt" in the URL :facepalm: 

Fixed in 978c3e98dc996d0eb177b0f98a7302bf0b4be0af
