### ISSUE TITLE
Node-Red pallette plugin not showing and custom command not working

### ISSUE THREAD

**Issue by infinitymakerspace** [synesthesiam/voice2json#24]
Hi guys, ok so I have installed the node-red plug in etc, I need to add an custom intent. On voice command it must trigger a node-red flow that has its own timer to run a relay for 20 to 40 seconds when invoked.  I have added words as well as intent but does not seem to work.  Also the Node-red plugin not available in my palette.  Tutorial feels like there is parts missing.

Any pointers would be greatly appreciated. Many thanks for all the help thus far

**Comment by synesthesiam** [comment]
I followed the [local installation instructions](https://nodered.org/docs/getting-started/local) and was successful in getting it running. After running `node-red-start`, I went to the `$HOME/.node-red` directory and ran:

```sh
$ npm install johanneskropf/node-red-contrib-voice2json
```

then restarted Node-RED to see the voice2json palette.

**Comment by infinitymakerspace** [comment]
Hi Michael

I will retry from within that directory and let you know

Many thanks

**Comment by infinitymakerspace** [comment]
Hi again.  

Ok node-red picks up palette, however

Its not accepting the path to my profile, its looking for kaldi, so I added a new path for pocketsphinx that is part of the voice2json tutorial but after adding or restart of nodered it still not reading it, I am still hetting a path error.

**Comment by infinitymakerspace** [comment]
![image](https://user-images.githubusercontent.com/61062911/87425920-c236bc00-c5de-11ea-919c-803bfc883387.png)

**Comment by infinitymakerspace** [comment]
Ok figured out and solved the Kaldi issue.  This is currently the only error I am receiving.

input audio not in the right format:wrong sample rate: should be 16000 Hznot mono: audio should only have 1 channel

**Comment by infinitymakerspace** [comment]
![image](https://user-images.githubusercontent.com/61062911/87434397-b9e47e00-c5ea-11ea-84b8-e57926f0eb7d.png)

**Comment by infinitymakerspace** [comment]
Ok just as an update voice transcribe from cli works, it picks up my custom sentence and intent, I am just facing that input issue of the audio
