### ISSUE TITLE
Update DeepSpeech to v0.9.3

### ISSUE THREAD

**Issue by solhuebner** [synesthesiam/voice2json#34]
Hi, awesome project :) As the newer DeepSpeech models are so much better, is there a way to update to the current version?

Or would you recommend using Rhasspy?

**Comment by synesthesiam** [comment]
Thanks! I'll be updating voice2json soon with new the DeepSpeech models. There are some other changes I want to include too :+1:

**Comment by synesthesiam** [comment]
Added in `master`. Will be updating the Docker images soon.

**Comment by synesthesiam** [comment]
Finally up in 2.1!

**Comment by solhuebner** [comment]
Thanks :)
