### ISSUE TITLE
getting 404's when trying to download Spanish profiles

### ISSUE THREAD

**Issue by Sondeluz** [synesthesiam/voice2json#45]
I am trying to get the spanish profiles with `voice2json --profile es download-profile`, and I'm getting 404's when it attempts to download them from github. 

All models fail except for the pocketsphinx one, and I was able to download the default english one too. I have attached the errors I get when trying to download the default "es" profile.

[404.txt](https://github.com/synesthesiam/voice2json/files/6644389/404.txt)

(Also: I'm using the latest Docker version)

**Comment by synesthesiam** [comment]
Thanks for the info! I've pushed a new Docker image with (hopefully) a fix. I had the wrong URL for the `es_kaldi-rhasspy` profile, which is set as the default Spanish profile.

Did you try `es_deepspeech-jaco` as well?

**Comment by Sondeluz** [comment]
Thank you :), I can confirm that now it's working correctly.  `es_deepspeech-jaco` is working too (I thought it wasn't but I probably derped)
