### ISSUE TITLE
Parsing of name substitution and optional in slots file gives wrong result.

### ISSUE THREAD

**Issue by johanneskropf** [synesthesiam/voice2json#6]
When I use an optional and name replacement like this in a a slot file called items for example:
```
([das] schlafzimmerlicht){item:Schlafzimmerlicht}
```
and use it in a sentences.ini like this:
```
[Licht]
($items) (einschalten:ON | ausschalten:OFF){command}
```
recognize intent will give me for the text `das schlafzimmerlicht ausschalten` the result:
` : Schlafzimmerlicht OFF` and in the slots:
```
item:" : Schlafzimmerlicht"
command:"OFF"
```
I dont think the ` : ` for the item slot should be there?
Johannes

**Comment by synesthesiam** [comment]
I just tested this on version 2 of voice2json, and it works now :)
