### ISSUE TITLE
error when installing from source

### ISSUE THREAD

**Issue by pfps** [synesthesiam/voice2json#85]
When I install from source I get the following error message from pip

Collecting rhasspy-asr-deepspeech~=0.4.0
  Downloading rhasspy-asr-deepspeech-0.4.0.tar.gz (4.6 kB)
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of pyyaml to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pydash to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of networkx to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of jsonlines to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of aiohttp to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of aiofiles to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of aioconsole to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of voice2json to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install voice2json because these package versions have conflicting dependencies.

The conflict is caused by:
    rhasspy-asr-deepspeech 0.4.1 depends on deepspeech==0.9.3
    rhasspy-asr-deepspeech 0.4.0 depends on deepspeech==0.9.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by pfps** [comment]
The problem may be that I am running Python 3.11 but deepspeech does not install for any Python newer than 3.6 (or maybe 3.9).

**Comment by ghost** [comment]
The error message indicates that there is a conflict between the dependencies of the rhasspy-asr-deepspeech package versions 0.4.0 and 0.4.1, both of which require `deepspeech==0.9.3.` One possible solution is to remove the specific version requirement for deepspeech in your installation command and allow pip to attempt to solve the dependency conflict automatically.

Another possibility, as suggested by the author of the package, is that deepspeech may not be compatible with Python versions newer than 3.6 or 3.9, while you may be running Python 3.11. In this case, you could try downgrading your Python version to a compatible one and then installing the package again.

Additionally, it's always a good practice to ensure that your package manager (pip in this case) is up-to-date before installing any packages, as outdated package managers can cause issues with package installations. You can upgrade pip using the command `python -m pip install --upgrade pip`.

**Comment by pfps** [comment]
Thanks.  I can't downgrade Python as my Linux system depends on it.   What I did was
```
./configure PYTHON=/usr/bin/python3.7
```
as Python 3.7 was installed on my system.

That seems to have fixed this problem.   But there should be a check in configure for the maximum version of Python that is permissable.

I was able to get further by only using kaldi text to speech but that failed during run time because of changes to some Python asynchronous package.   Using Python 3.7 fixed this problem as well.

**Comment by ghost** [comment]
Okay i hope so you will fix can you mark as answer the my previous answer? Thanks

**Comment by pfps** [comment]
How does one add the correct answer marker in GitHub?  I can close this issue as completed/... but I don't know how add an answer marker.

**Comment by ghost** [comment]
oh my mistake that's an issue only can possible discussions. No worries 👍 Have a nice codings!
