### ISSUE TITLE
Set locales for docker build

### ISSUE THREAD

**Issue by johanneskropf** [synesthesiam/voice2json#9]
Docker cant be used for German Profiles as it gives asci decode errors while training. This is probably due to missing locales in the docker container.

**Comment by synesthesiam** [comment]
Yes, I believe the missing line is:

```
ENV LANG C.UTF-8
```

I'm working on the next version of voice2json now, which has this in it. Unfortunately, I'm not in a state where it'd be easy to switch back and fix the original Dockerfile :/

**Comment by johanneskropf** [comment]
Any rough guesses on an eta 🙈?

**Comment by synesthesiam** [comment]
Was hoping for today, but looks like it might be tomorrow :monkey_face:

**Comment by johanneskropf** [comment]
> ENV LANG C.UTF-8

wouldn't you have to explicitly also include de_DE.utf-8 because of the german ä ö ü ß and so on for the other supported languages and their special characters?

**Comment by synesthesiam** [comment]
I don't think so, though I'm not a UTF expert by any means. I don't see training errors when testing the [default German sentences](https://github.com/synesthesiam/de_pocketsphinx-cmu/blob/master/sentences.ini), at least.

**Comment by johanneskropf** [comment]
Is this fix in the docker file on docker hub already? Than i could try it.
